require('dotenv').config();
var express = require('express');
// var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var transactionRouter = require('./routes/transactionRoute');
let cors=require('cors');
var app = express();
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(cors());
app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/transactions', transactionRouter);
module.exports = app;
